import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  maincontainer: {
    flex: 1,
  },
  container: {
    height: 120,
    backgroundColor: '#ffff',
    borderRadius: 20,
    marginTop: 18,
    flexDirection: 'row',
    width: '94%',
    paddingLeft: 10,
    bottom: 18,
    alignSelf: 'center',
    elevation: 10,
    padding: 10,
  },
  foodmenuitems: {
    flexDirection: 'column',
    marginLeft: 10,
    marginTop: 5,
  },
  flatliststyle: {
    marginTop: 10,
    marginBottom: 10,
  },
  Maintext: {
    fontSize: 26,
    color: 'black',
    fontFamily: 'VarelaRound-Regular',
    marginLeft: 25,
    top: 5,
  },
  Maintext2: {
    fontSize: 26,
    color: 'black',
    fontFamily: 'VarelaRound-Regular',
    marginLeft: 25,
    top: 5,
    marginBottom: 10,
  },
  adminlogo: {
    height: 60,
    width: 60,
    borderRadius: 40,
    alignSelf: 'center',
  },
  name: {
    fontSize: 15,
    letterSpacing: 1,
    color: 'black',
    fontFamily: 'VarelaRound-Regular',
  },

  price: {
    fontSize: 15,
    letterSpacing: 1,
    color: 'grey',
    fontFamily: 'VarelaRound-Regular',
  },
  totalamounttextview: {
    height: 40,
    backgroundColor: '#ffff',
    borderRadius: 20,
    marginTop: 15,
    marginHorizontal: 20,
    justifyContent: 'flex-start',
    flexDirection: 'row',
    marginBottom: 20,
  },
  totalamounttext: {
    marginLeft: 20,
    marginRight: 180,
    fontFamily: 'VarelaRound-Regular',
    color: 'black',
    fontSize: 15,
    marginTop: 10,
  },
  button: {
    borderRadius: 18,
    backgroundColor: '#ff8b3d',
    height: 60,
    width: 340,
    marginTop: 20,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  buttontext: {
    color: 'white',
    fontSize: 18,
    justifyContent: 'center',
    alignSelf: 'center',
    fontFamily: 'VarelaRound-Regular',
  },
  finalprice: {
    fontFamily: 'VarelaRound-Regular',
    color: 'black',
    fontSize: 15,
    marginTop: 10,
  },
});
export default styles;
